### PR TITLE
Danger

### LINKED ISSUE #102: Report linting warnings to PR
Our CI is printing linter errors/warnings just fine, but the results aren't visible to the PR creators. - which kinda sucks, right? 😜
Do you know how to achieve this @pixyzehn?
One thing that comes to my mind is to introduce [Danger](https://github.com/danger/danger) ([since buddybuild uses it without any issues](https://github.com/danger/danger/issues/695)) and use something like [this](https://github.com/ashfurrow/danger-swiftlint).

### PR DESCRIPTION
**Pull request by cojoj**
Closes #102 

Added `Gemfile` with our Ruby dependencies, updated `swiftlint.yml`, cause it had some issues with correctly checking files, simplified `boddybuild_postclone`, created very basic `Dangerfile`.

### CODE REVIEW

**Comment by JohnSundell** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is classed as Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by cojoj** [comment]
Hahaha, @JohnSundell you'll be the _bad guy_ reporting all the bad things 😂 Seems like it works. I'll have to add more stuff to Dangerfile, but it's nice it works out of the box ❤️

**Comment by JohnSundell** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a summary in the Pull Request description</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by JohnSundell** [comment]
Haha 😅 We should be able to configure that to say "DangerBot" or something.

**Comment by cojoj** [comment]
@JohnSundell to do so I'll need access to BuddyBuild or you'll have to create **Bot** and add it. I have account on BuddyBuild, so I guess you can invite me, but I guess I'll be able to finish this no sooner than Tuesday (going to the wedding 👰)

**Comment by cojoj** [comment]
@JohnSundell I'll kindly ask you to [follow these steps](http://danger.systems/guides/getting_started.html#creating-a-bot-account-for-danger-to-use) and add the `DANGER_GITHUB_API_TOKEN` to Bot's build ENV. We shouldn't have any further _changes_ in this PR as from now on buddybuild should handle everything correctly (Gemfile and Dangerfile are present).
We may wan to create a special doc for our guidelines, but I don't think it's necessary as Danger will handle everything and report it, so it's way more convenient and one less thing to maintain. I'd rather take a look at other projects and see some Danger checks for which we can benefit as well, but I guess I'll just propose them (if I find anything) in #102.

**Pull request closed without merging**
