### PR TITLE
Run Swift command line tools through xcrun

### PR DESCRIPTION
**Pull request by JohnSundell**
With this change, the Swift command line tools and compiler are always invoked using xcrun on macOS, with explicit SDK settings. This enables Marathon to be run from within another xcodebuild process (such as a “run script phase” in Xcode).

So you can now write build scripts in Swift! 🎉

### CODE REVIEW

**Comment by darthpelo** [comment]
@JohnSundell I will give an in-depth reading, I don't remember if I had similar errors with the tests.

**Comment by darthpelo** [comment]
@JohnSundell I don't have experience with Travis, but this error it's strange:

> Test Case 'MarathonTests.testAddingAndRemovingRemotePackage' started at 19:22:46.962
> <EXPR>:0: error: MarathonTests.testAddingAndRemovingRemotePackage : threw error "💥  Cannot remove package 'files' - no such package has been added
> 👉  Did you mean to remove the cache data for a script? If so, add '.swift' to its path
>    To list all added packages run 'marathon list'"

because it was solved #49 🤔

**Comment by JohnSundell** [comment]
@darthpelo Maybe it's the case sensitivity problem again, I'll try changing to `remove Files`.

**Comment by JohnSundell** [comment]
Ah, we already had an issue for that 😅 https://github.com/JohnSundell/Marathon/issues/50.

**Comment by JohnSundell** [comment]
I've solved all issues except for the installation one, will try to find a Linux box somewhere to debug this 😅

**Comment by kareman** [comment]
This might be helpful: https://docs.travis-ci.com/user/common-build-problems/#Running-a-Container-Based-Docker-Image-Locally .

**Comment by JohnSundell** [comment]
@kareman Thank you, but first I need to actually be able to run Linux. Have been putting this up, but looks unavoidable now 😝

**Comment by JohnSundell** [comment]
Probably for the better, I know have a good reason to get into Swift on Linux 😄

**Comment by JohnSundell** [comment]
Wohooo! All tests are passing 🎉 We now have CI for Linux 🚀 Thanks a lot @kareman & @darthpelo for your help 👍

**Pull request merged**
