### PR TITLE
Use swiftenv local version

### PR DESCRIPTION
**Pull request by pixyzehn**
I just improved the setting of TravisCI.

- Use the version of `.swift-version` file generated by `swiftenv local 3.1`.
- Add `swift build ` in a script phase.

See also: https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html

### CODE REVIEW

**Comment by JohnSundell** [comment]
@pixyzehn Seems like the Travis CI build is failing though 😮

**Comment by pixyzehn** [comment]
@JohnSundell Fixed:)

**Comment by pixyzehn** [comment]
@JohnSundell 
That's right. This was my preference. I took it out:)

> It is no longer necessary to run swift build before running swift test (it will always regenerates the build manifest when necessary). In addition, it now accepts (and requires) the same -Xcc, etc. options as are used with swift build

https://github.com/apple/swift-package-manager/blob/43cc5da9ef3e65d9b6bff555b4d18866abd5b0a0/CHANGELOG.md#swift-30

**Comment by JohnSundell** [comment]
@pixyzehn so what improvement does this PR bring over the current CI script? 🤔

**Comment by pixyzehn** [comment]
I thought it's better to use `.swift-version` just for clarity if we use swiftenv in Travis.
If you don't think so, I'll close👍

**Comment by pixyzehn** [comment]
Thanks:)

**Pull request merged**
