### PR TITLE
Update project to Swift 4.1 and make compatible with SPM 4.1

### PR DESCRIPTION
**Pull request by JohnSundell**
This change makes Marathon compatible with the Swift 4.1 toolchain, including the 4.1 version of SPM. The biggest change is the removal of the prefetching flag and fixing of some deprecation warnings.

Also includes a fix for the `testEditingScriptWithXcodeOnMacOS` test that was failing on master.

### CODE REVIEW

**Comment by orta** [comment]
So much red 😝

**Comment by JohnSundell** [comment]
WIP 😅 All tests are passing locally but need to figure out why they're not passing on CI (esp. Linux).

**Comment by JohnSundell** [comment]
We're down to *only* two failures 😅 Getting close!

**Comment by designatednerd** [comment]
@johnsundell FWIW I just checked this branch out and it Works On My Machine™

**Comment by JohnSundell** [comment]
@designatednerd Hehe that's good to know. The problem is (was?, hopefully!) on Linux. Hopefully it's fixed now 😅 I really need to get that Linux environment up and running so I can more easily debug these things.

**Comment by rob-nash** [comment]
FYI one of the dependencies 'releases' has some deprecations. Not sure if that might upset your CI build. It's a long shot

I run `make` on latest commit on this branch. Checkout 2d8f59b00b7d6fb3dd5e475713d4515e5a559b30

Output

```
///stuff
Resolving https://github.com/JohnSundell/Require.git at 2.0.1
swift build -c release -Xswiftc -static-stdlib
Compile Swift Module 'Require' (1 sources)
Compile Swift Module 'Unbox' (42 sources)
Compile Swift Module 'Wrap' (1 sources)
Compile Swift Module 'ShellOut' (1 sources)
Compile Swift Module 'Files' (1 sources)
Compile Swift Module 'Releases' (4 sources)
/Users/robertnash/Code/Marathon/.build/checkouts/Releases.git--3309408284261296015/Sources/Releases.swift:26:26: warning: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value
        return try lines.flatMap { line in
                         ^
/Users/robertnash/Code/Marathon/.build/checkouts/Releases.git--3309408284261296015/Sources/Releases.swift:26:26: note: use 'compactMap(_:)' instead
        return try lines.flatMap { line in
                         ^~~~~~~
                         compactMap
Compile Swift Module 'MarathonCore' (29 sources)
Compile Swift Module 'Marathon' (1 sources)
Linking ./.build/x86_64-apple-macosx10.10/release/Marathon
mkdir -p /usr/local/bin
mv .build/Release/Marathon .build/Release/marathon
install .build/Release/marathon /usr/local/bin
Roberts-iMac:Marathon robertnash$ 
```

**Comment by JohnSundell** [comment]
OK @sunshinejr comes to the rescue and seems to have fixed the problem! 🚀 Let's see if we finally get it to turn green 😃

**Comment by JohnSundell** [comment]
It's time to pop the 🍾! 😃 Thanks a lot to @sunshinejr for helping me finalize this 🙌

**Pull request merged**
